  on:
    push:
  jobs:
    test:
     runs-on: ubuntu-latest
     steps:
     - name: Run E2E Test
       uses: apache/skywalking-infra-e2e@main
       with:
         e2e-file: $GITHUB_WORKSPACE/test/e2e-v2/cases/mysql/prometheus-mysql-exporter/e2e.yaml
